const  express = require("express");
const categoryRouter = express.Router();
const {CategoryController} = require("../controllers/categorycontroller");
categoryRouter.post("/create",CategoryController.create);
categoryRouter.get("/get-data",CategoryController.read);
categoryRouter.get("/trash-get-data",CategoryController.trashGetData);
categoryRouter.delete("/delete/:id",CategoryController.deletefuction);
categoryRouter.patch("/move-to-trash/:id",CategoryController.moveToTrash);
categoryRouter.patch("/change-status",CategoryController.changeStatus);
categoryRouter.patch("/restore/:id",CategoryController.restoreFuc);
module.exports = categoryRouter;  