import {ToastContainer} from 'react-toastify';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "../globals.css";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ToastContainer position="bottom-right"/>
      {children}</body>
    </html>
  )
}
